//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsCentral.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsCentral.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Notes.
        /// </summary>
        public static string ApprovalNotes {
            get {
                return ResourceManager.GetString("ApprovalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvals.
        /// </summary>
        public static string Approvals {
            get {
                return ResourceManager.GetString("Approvals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string ApprovedBy {
            get {
                return ResourceManager.GetString("ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date.
        /// </summary>
        public static string ApprovedDate {
            get {
                return ResourceManager.GetString("ApprovedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsCentral.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Dashboard.
        /// </summary>
        public static string BackToDashboard {
            get {
                return ResourceManager.GetString("BackToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Presentations.
        /// </summary>
        public static string BackToPresentations {
            get {
                return ResourceManager.GetString("BackToPresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Text.
        /// </summary>
        public static string BodyText {
            get {
                return ResourceManager.GetString("BodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to Action.
        /// </summary>
        public static string CallToAction {
            get {
                return ResourceManager.GetString("CallToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Assignment.
        /// </summary>
        public static string CreateAssignment {
            get {
                return ResourceManager.GetString("CreateAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Presentation.
        /// </summary>
        public static string CreatePresentation {
            get {
                return ResourceManager.GetString("CreatePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect.
        /// </summary>
        public static string CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days of Week.
        /// </summary>
        public static string DaysOfWeek {
            get {
                return ResourceManager.GetString("DaysOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Presentation.
        /// </summary>
        public static string DeletePresentation {
            get {
                return ResourceManager.GetString("DeletePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Presentation.
        /// </summary>
        public static string EditPresentation {
            get {
                return ResourceManager.GetString("EditPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error publishing: {0}.
        /// </summary>
        public static string ErrorPublishing {
            get {
                return ResourceManager.GetString("ErrorPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Poster.
        /// </summary>
        public static string GeneratedPoster {
            get {
                return ResourceManager.GetString("GeneratedPoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headline Text.
        /// </summary>
        public static string HeadlineText {
            get {
                return ResourceManager.GetString("HeadlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image selected.
        /// </summary>
        public static string ImageSelected {
            get {
                return ResourceManager.GetString("ImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image must be smaller than 10MB.
        /// </summary>
        public static string ImageTooLarge {
            get {
                return ResourceManager.GetString("ImageTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string IndexManagement_AccessDenied {
            get {
                return ResourceManager.GetString("IndexManagement.AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only system administrators can access this page..
        /// </summary>
        public static string IndexManagement_AccessDeniedMessage {
            get {
                return ResourceManager.GetString("IndexManagement.AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IndexManagement_ActiveAssignments {
            get {
                return ResourceManager.GetString("IndexManagement.ActiveAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate index files for all teams. This is useful after bulk data changes or troubleshooting..
        /// </summary>
        public static string IndexManagement_AllTeamsDescription {
            get {
                return ResourceManager.GetString("IndexManagement.AllTeamsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Teams Indexes.
        /// </summary>
        public static string IndexManagement_AllTeamsSection {
            get {
                return ResourceManager.GetString("IndexManagement.AllTeamsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Team.
        /// </summary>
        public static string IndexManagement_CurrentTeam {
            get {
                return ResourceManager.GetString("IndexManagement.CurrentTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Team Index.
        /// </summary>
        public static string IndexManagement_CurrentTeamSection {
            get {
                return ResourceManager.GetString("IndexManagement.CurrentTeamSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string IndexManagement_ExpiredAssignments {
            get {
                return ResourceManager.GetString("IndexManagement.ExpiredAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Exists.
        /// </summary>
        public static string IndexManagement_IndexExists {
            get {
                return ResourceManager.GetString("IndexManagement.IndexExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Generated.
        /// </summary>
        public static string IndexManagement_LastGenerated {
            get {
                return ResourceManager.GetString("IndexManagement.LastGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string IndexManagement_No {
            get {
                return ResourceManager.GetString("IndexManagement.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No team selected. Please select a team from the home page..
        /// </summary>
        public static string IndexManagement_NoTeamSelected {
            get {
                return ResourceManager.GetString("IndexManagement.NoTeamSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage and regenerate index.json files for teams.
        /// </summary>
        public static string IndexManagement_PageDescription {
            get {
                return ResourceManager.GetString("IndexManagement.PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Management.
        /// </summary>
        public static string IndexManagement_PageTitle {
            get {
                return ResourceManager.GetString("IndexManagement.PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate All Team Indexes.
        /// </summary>
        public static string IndexManagement_RegenerateAllTeams {
            get {
                return ResourceManager.GetString("IndexManagement.RegenerateAllTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Current Team Index.
        /// </summary>
        public static string IndexManagement_RegenerateCurrentTeam {
            get {
                return ResourceManager.GetString("IndexManagement.RegenerateCurrentTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerating....
        /// </summary>
        public static string IndexManagement_Regenerating {
            get {
                return ResourceManager.GetString("IndexManagement.Regenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerating All....
        /// </summary>
        public static string IndexManagement_RegeneratingAll {
            get {
                return ResourceManager.GetString("IndexManagement.RegeneratingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully regenerated {0} of {1} team indexes!.
        /// </summary>
        public static string IndexManagement_RegenerationAllSuccess {
            get {
                return ResourceManager.GetString("IndexManagement.RegenerationAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string IndexManagement_RegenerationError {
            get {
                return ResourceManager.GetString("IndexManagement.RegenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index regenerated successfully for {0}!.
        /// </summary>
        public static string IndexManagement_RegenerationSuccess {
            get {
                return ResourceManager.GetString("IndexManagement.RegenerationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string IndexManagement_Team {
            get {
                return ResourceManager.GetString("IndexManagement.Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Assignments.
        /// </summary>
        public static string IndexManagement_TotalAssignments {
            get {
                return ResourceManager.GetString("IndexManagement.TotalAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string IndexManagement_UpcomingAssignments {
            get {
                return ResourceManager.GetString("IndexManagement.UpcomingAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string IndexManagement_Yes {
            get {
                return ResourceManager.GetString("IndexManagement.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid image file.
        /// </summary>
        public static string InvalidImageType {
            get {
                return ResourceManager.GetString("InvalidImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingPleaseWait {
            get {
                return ResourceManager.GetString("LoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Assignments.
        /// </summary>
        public static string MyAssignments {
            get {
                return ResourceManager.GetString("MyAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMINISTRATION.
        /// </summary>
        public static string NavMenu_AdminSection {
            get {
                return ResourceManager.GetString("NavMenu.AdminSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvals.
        /// </summary>
        public static string NavMenu_Approvals {
            get {
                return ResourceManager.GetString("NavMenu.Approvals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string NavMenu_Assignments {
            get {
                return ResourceManager.GetString("NavMenu.Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavMenu_Home {
            get {
                return ResourceManager.GetString("NavMenu.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Management.
        /// </summary>
        public static string NavMenu_IndexManagement {
            get {
                return ResourceManager.GetString("NavMenu.IndexManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string NavMenu_Schedules {
            get {
                return ResourceManager.GetString("NavMenu.Schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavMenu_Settings {
            get {
                return ResourceManager.GetString("NavMenu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Management.
        /// </summary>
        public static string NavMenu_TeamManagement {
            get {
                return ResourceManager.GetString("NavMenu.TeamManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string NavMenu_UserManagement {
            get {
                return ResourceManager.GetString("NavMenu.UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assignments yet.
        /// </summary>
        public static string NoAssignmentsYet {
            get {
                return ResourceManager.GetString("NoAssignmentsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pending Approvals.
        /// </summary>
        public static string NoPendingApprovals {
            get {
                return ResourceManager.GetString("NoPendingApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Image.
        /// </summary>
        public static string OriginalImage {
            get {
                return ResourceManager.GetString("OriginalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully!.
        /// </summary>
        public static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters.
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval.
        /// </summary>
        public static string PendingApproval {
            get {
                return ResourceManager.GetString("PendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Your Approval.
        /// </summary>
        public static string PendingYourApproval {
            get {
                return ResourceManager.GetString("PendingYourApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image.
        /// </summary>
        public static string PleaseSelectImage {
            get {
                return ResourceManager.GetString("PleaseSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster Preview.
        /// </summary>
        public static string PosterPreview {
            get {
                return ResourceManager.GetString("PosterPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentations.
        /// </summary>
        public static string Presentations {
            get {
                return ResourceManager.GetString("Presentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published By.
        /// </summary>
        public static string PublishedBy {
            get {
                return ResourceManager.GetString("PublishedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Date.
        /// </summary>
        public static string PublishedDate {
            get {
                return ResourceManager.GetString("PublishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing....
        /// </summary>
        public static string Publishing {
            get {
                return ResourceManager.GetString("Publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Publish.
        /// </summary>
        public static string ReadyToPublish {
            get {
                return ResourceManager.GetString("ReadyToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection Reason.
        /// </summary>
        public static string RejectionReason {
            get {
                return ResourceManager.GetString("RejectionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require approval.
        /// </summary>
        public static string RequireApproval {
            get {
                return ResourceManager.GetString("RequireApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Team.
        /// </summary>
        public static string SourceTeam {
            get {
                return ResourceManager.GetString("SourceTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully published to {0}.
        /// </summary>
        public static string SuccessfullyPublished {
            get {
                return ResourceManager.GetString("SuccessfullyPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Team.
        /// </summary>
        public static string TargetTeam {
            get {
                return ResourceManager.GetString("TargetTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Presentations.
        /// </summary>
        public static string ViewPresentations {
            get {
                return ResourceManager.GetString("ViewPresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, {0}!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
