<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NewsCentral</RootNamespace>
    <AssemblyName>NewsCentral.Shared</AssemblyName>
  </PropertyGroup>

</Project>
